// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// reallocateTime_
DataFrame reallocateTime_(DataFrame d, const float t_discharge, const float frequency);
RcppExport SEXP ccdata_reallocateTime_(SEXP dSEXP, SEXP t_dischargeSEXP, SEXP frequencySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type d(dSEXP);
    Rcpp::traits::input_parameter< const float >::type t_discharge(t_dischargeSEXP);
    Rcpp::traits::input_parameter< const float >::type frequency(frequencySEXP);
    __result = Rcpp::wrap(reallocateTime_(d, t_discharge, frequency));
    return __result;
END_RCPP
}
