# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reallocateTime_ <- function(d, t_discharge, frequency) {
    .Call('cleanEHR_reallocateTime_', PACKAGE = 'cleanEHR', d, t_discharge, frequency)
}

reallocateTime__ <- function(d, t_admission, t_discharge, frequency) {
    .Call('cleanEHR_reallocateTime__', PACKAGE = 'cleanEHR', d, t_admission, t_discharge, frequency)
}

