# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reallocateTime_ <- function(d, t_discharge, frequency) {
    .Call('ccdata_reallocateTime_', PACKAGE = 'ccdata', d, t_discharge, frequency)
}

